import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.woff",
  variable: "--font-satoshi",
  weight: "100 900",
});
const integral = localFont({
  src: "./fonts/IntegralCF-Bold.woff",
  variable: "--font-integral",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable}  antialiased`}
      >
        <div className={`${integral.variable}`}>
          {children}
        </div>
      </body>
    </html>
  );
}
